[package]
name = "rusty-film"
description = "An opinionated filesystem-based photo management tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
enum_dispatch = "0.3.13"
indicatif = { version = "0.17.8", features = ["tokio"] }
kamadak-exif = "0.5.5"
tokio = { version = "1.37.0", features = ["full"] }
